CREATE DATABASE sistemas_reserva;
USE sistemas_reserva;

CREATE TABLE reserva (
Id INT AUTO_INCREMENT PRIMARY KEY,
Cursos VARCHAR(50) NOT NULL,
Ofertas VARCHAR(50) NOT NULL,
Sigla VARCHAR (10) NOT NULL,
Codigo_turma INT NOT NULL,
Data_inicio INT NOT NULL,
Data_fim INT NOT NULL,
Subarea VARCHAR(30) NOT NULL,
Docente VARCHAR(100) NOT NULL,
Sala_lab VARCHAR (100) NOT NULL,
Capacidade INT NOT NULL
);

CREATE TABLE cadastro (
Id INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Senha VARCHAR(50) NOT NULL
);


